
from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config


# !!!! SELECT MODE !!!!
MODE = "DEVELOPMENT"

# Close all open positions and orders
ABORT_ALL_POSITIONS = True

# Find Cointegrated Pairs
FIND_COINTEGRATED = True

# Manage Exits
MANAGE_EXITS = True

# Place Trades
PLACE_TRADES = True

# Resolution
RESOLUTION = "1HOUR"
#STATS WINDOW

WINDOW = 21

#THRESHOLDS - OPENING

MAX_HALF_LIFE = 24
ZSCORE_THRESH = 1.5
USD_PER_TRADE = 50
USD_MIN_COLLATERAL = 1000

#THRESHOLDS - CLOSING

CLOSE_AT_ZSCORE_CROSS = True

#ETHEREUM ADDRESS
ETHEREUM_ADDRESS = "0x5437F1C821e41399BCa1FD6271a3434fc533EF00"

# KEYS - PRODUCTION
# MUST TO BE ON MAINNET ON DYDX
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")


# KEYS - DEVELOPMENT
# MUST TO BE ON TESTNET ON DYDX
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

# keys - Export
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET

# Host provider
HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_GOERLI

 # Http Provider

HTTP_PROVIDER_TESTNET ="https://eth-goerli.g.alchemy.com/v2/5LARqbnGFzixmYTVgYyD9ULuIBjW0Pqa"
HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/3byuvDLV9lehPWWVPIR76cWTYtf-EC5b"
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET

